### ISSUE TITLE
Support HelpScouts new Mailbox 2.0 API

### ISSUE THREAD

**Issue by mathetos** [webzunft/edd-helpscout#55]
HelpScout will deprecate their old API on June 5, 2019. Hoping you can get ahead of that so there's a smooth and seamless migration to the new API. 

See here:
https://developer.helpscout.com/mailbox-api/

and here:
https://developer.helpscout.com/mailbox-api/overview/v1-v2-differences/

Thanks!

**Comment by webzunft** [comment]
Thanks for the reminder.

Right now, I am waiting for their PHP wrapper to get V2 into master so that I can be sure that it is stable enough. According to https://github.com/helpscout/helpscout-api-php, this should happen on April 1st.

I hope to make the deadline, but any help is appreciated. Contributions I could think of are:

* contribute the code to migrate the API key for the OAuth token, https://developer.helpscout.com/mailbox-api/migration/transition-service/
* creating a new OAuth token for new users
* list deprecated function and suggest their replacement

**Comment by webzunft** [comment]
@mathetos I think I slept while reviewing it. The plugin does not use the Help Scout API (I do in other projects so this is still relevant to me). The plugin itself is the API endpoint for the Help Scout App, but the Mailbox API is not involved here.

**Comment by mathetos** [comment]
Ha! Yes... I see what you mean. Makes sense. I'm getting these API notices from HelpScout all the time and we love this plugin so wanted to make sure the transition was smooth. Glad it will be. Thanks!
